version: '3.8'

services:
  face-api:
    container_name: face-api
    image: controleinternofacedetectapi-face-api:latest
    build: 
     context: .
     network: host
    ports:
      - "7400:7400"
      - "443:443"
    environment:
      - FLASK_ENV=production
    networks:
      - controle-interno-network

networks:
  controle-interno-network:
    external: true
