version: '3.8'

services:
  face-api:
    container_name: face-api
    build: 
      context: .
      network: host
    ports:
      - "7400:7400"
    environment:
      - FLASK_ENV=production
      
    network_mode: "host"