version: '3.8'

services:
  face-api:
    container_name: face-api
    image: face-api:v1.0
    build:
      context: .
      network: host
    ports:
      - "9090:7400"
    environment:
      - FLASK_ENV=production
    networks:
      - controle-interno-network
    restart: always

  nginx:
    image: nginx:1.24.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - face-api
    restart: always

networks:
  controle-interno-network:
    external: true
