name: Build and Deploy Image Docker

on:
  push:
    branches: ["main"]
    tags: 
      - v1.*
  pull_request:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_container: "face-api"
      docker_tag_version: "v1.0"
      DOCKER_REGISTRY: "docker.io"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag or branch
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          else
            VERSION_TAG=${GITHUB_SHA}
          fi
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Run Dockerfile & Deploy Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/face-recognition:${{ env.VERSION_TAG }}
      
